encoder:
  _target_: models.encoder.Encoder

  dim: 128
  scale: 1.0
  middle: [2, 2]

  backbone:
    _target_: models.backbones.efficientnet.EfficientNetExtractor

    model_name: efficientnet-b4
    layer_names: ['reduction_2', 'reduction_4']
    image_height: ${data.image.h}
    image_width: ${data.image.w}

  cross_view:
    _target_: utils.attention.CrossViewAttention

    heads: 4
    dim_head: 32
    qkv_bias: True
    skip: True
    no_image_features: False

    image_height: ${data.image.h}
    image_width: ${data.image.w}

  bev_embedding:
    _target_: utils.utils.BEVEmbedding

    sigma: 1.0

    bev_height: ${data.bev.h}
    bev_width: ${data.bev.w}
    h_meters: ${data.bev.h_meters}
    w_meters: ${data.bev.w_meters}
    offset: ${data.bev.offset}
